In [1]:
from CPT import *

In [2]:
model = CPT()
data, target = model.load_files("./data/train.csv", "./data/test.csv")

In [3]:
model.train(data)

True

In [4]:
predictions = model.predict(data,[['1', '2', 3, 4, 5], [6, 7, 8, 9], [1, 2, 3, 4, 5]],6,2)

100%|██████████| 3/3 [00:02<00:00,  1.27it/s]


In [5]:
import random

In [6]:
tar = [random.randint(2000, 3000) for i in range(50)]

In [7]:
target[:10]

[[23855, 23933, 24917, 24915, 23714, 23663, 24958, 25135, 25727, 24530],
 [23663, 23855, 24917, 23933, 23975, 23714, 25135, 24915, 24958, 23781],
 [26939, 26940, 26941, 26942, 26943, 26944, 26945, 26947, 26948, 26954],
 [23663, 23855, 23975, 23714, 23848, 23933, 25135, 23781, 24530, 23667],
 [23855, 23975, 25135, 23848, 23714, 24917, 23929, 25733, 25126, 23913],
 [23714, 23855, 23933, 25126, 23663, 25135, 24530, 23975, 24527, 23648],
 [23663, 23933, 24917, 24958, 23648, 23714, 23781, 23975, 24915, 24530],
 [26157, 26158, 26159, 26160, 26161, 26162, 26164, 26165, 26163, 26166],
 [23855, 24917, 24958, 23836, 24915, 23933, 23663, 23714, 23975, 24261],
 [26157, 26158, 26160, 26161, 26162, 26164, 26165, 26163, 26166, 26167]]

In [8]:
model.predict(data,[[23855, 23, 24917, 42, 23714, 43, 24530, 12, 25727, 89,23714, 43, 24530]],6,10)

100%|██████████| 1/1 [00:00<00:00, 125.09it/s]


[[25135, 23663, 24958, 23880, 23933, 25126, 26052, 23999, 23691, 26051]]

In [9]:
predictions

[[], [], []]

In [10]:
target[6:10]

[[23663, 23933, 24917, 24958, 23648, 23714, 23781, 23975, 24915, 24530],
 [26157, 26158, 26159, 26160, 26161, 26162, 26164, 26165, 26163, 26166],
 [23855, 24917, 24958, 23836, 24915, 23933, 23663, 23714, 23975, 24261],
 [26157, 26158, 26160, 26161, 26162, 26164, 26165, 26163, 26166, 26167]]

In [2]:
import random

In [3]:
targ = [23663, 23933, 24917, 24958, 23648, 23714, 23781, 23975, 24915, 24530]

In [4]:
max(targ)

24958

## Method 2

In [2]:
data = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]
print(data)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]


In [3]:
import numpy as np
def splitSequence(seq, n_steps):
    
    #Declare X and y as empty list
    X = []
    y = []
    
    for i in range(len(seq)):
        #get the last index
        lastIndex = i + n_steps
        
        #if lastIndex is greater than length of sequence then break
        if lastIndex > len(seq) - 1:
            break
            
        #Create input and output sequence
        seq_X, seq_y = seq[i:lastIndex], seq[lastIndex]
        
        #append seq_X, seq_y in X and y list
        X.append(seq_X)
        y.append(seq_y)
        pass
    #Convert X and y into numpy array
    X = np.array(X)
    y = np.array(y)
    
    return X,y 
    
    pass

In [4]:
n_steps = 5
X, y = splitSequence(data, n_steps = 5)

In [5]:
print(X)

[[ 10  20  30  40  50]
 [ 20  30  40  50  60]
 [ 30  40  50  60  70]
 [ 40  50  60  70  80]
 [ 50  60  70  80  90]
 [ 60  70  80  90 100]
 [ 70  80  90 100 110]
 [ 80  90 100 110 120]
 [ 90 100 110 120 130]
 [100 110 120 130 140]
 [110 120 130 140 150]
 [120 130 140 150 160]
 [130 140 150 160 170]
 [140 150 160 170 180]
 [150 160 170 180 190]]


In [6]:
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
print(X[:2])

[[[10]
  [20]
  [30]
  [40]
  [50]]

 [[20]
  [30]
  [40]
  [50]
  [60]]]


In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [8]:
model = tf.keras.Sequential()
model.add(layers.LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(layers.Dense(1))

In [9]:
model.layers

In [10]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 50)                10400     
                                                                 
 dense (Dense)               (None, 1)                 51        
                                                                 
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [11]:
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), loss=tf.keras.losses.MeanSquaredError(), metrics=['accuracy'])

In [12]:
model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
1/1 [==============================] - 2s 2s/step - loss: 20058.4746 - accuracy: 0.0000e+00
Epoch 2/200
1/1 [==============================] - 0s 6ms/step - loss: 16476.9473 - accuracy: 0.0000e+00
Epoch 3/200
1/1 [==============================] - 0s 7ms/step - loss: 15203.9775 - accuracy: 0.0000e+00
Epoch 4/200
1/1 [==============================] - 0s 7ms/step - loss: 13176.0879 - accuracy: 0.0000e+00
Epoch 5/200
1/1 [==============================] - 0s 7ms/step - loss: 8769.3115 - accuracy: 0.0000e+00
Epoch 6/200
1/1 [==============================] - 0s 8ms/step - loss: 500.2924 - accuracy: 0.0000e+00
Epoch 7/200
1/1 [==============================] - 0s 5ms/step - loss: 7790.9443 - accuracy: 0.0000e+00
Epoch 8/200
1/1 [==============================] - 0s 6ms/step - loss: 2355.7297 - accuracy: 0.0000e+00
Epoch 9/200
1/1 [==============================] - 0s 7ms/step - loss: 240.6366 - accuracy: 0.0000e+00
Epoch 10/200
1/1 [==============================] - 0s 6ms/step

In [13]:
test_data = np.array([90, 100, 110, 120, 130])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[ 90],
        [100],
        [110],
        [120],
        [130]]])

In [14]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 250ms/step
[[140.08351]]


In [15]:
test_data = np.array([160, 170, 180, 190, 200])
test_data = test_data.reshape((1, n_steps, n_features))
test_data

array([[[160],
        [170],
        [180],
        [190],
        [200]]])

In [16]:
predictNextNumber = model.predict(test_data, verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 30ms/step
[[211.65868]]


In [17]:
predictNextNumber

array([[211.65868]], dtype=float32)

In [18]:
import random

In [19]:
test = [[random.randint(1000, 10000)] for i in range(10)]
test

[[9295],
 [2437],
 [3354],
 [8227],
 [6551],
 [3486],
 [7442],
 [4703],
 [4279],
 [3254]]

In [20]:
test

[[9295],
 [2437],
 [3354],
 [8227],
 [6551],
 [3486],
 [7442],
 [4703],
 [4279],
 [3254]]

In [21]:
predictNextNumber = model.predict([[[1], [2], [3], [4], [5] ]], verbose=1)
print(predictNextNumber)

1/1 [==============================] - 0s 54ms/step
[[10.85879]]


In [27]:
test_data

array([[[160],
        [170],
        [180],
        [190],
        [200]]])

In [6]:
import numpy as np
def getSeq(inp, num):
    diff = np.diff(np.array(inp))
    d = sum(diff)/len(diff)
    d = round(d)
    print(np.diff(np.array(inp)))
    seq = [round(i) for i in np.arange(inp[-1]+d, inp[-1]+(d*num+1), d)]
    return seq

In [7]:
getSeq([1,2, 3, 4, 5, 6], 5)

[1 1 1 1 1]


[7, 8, 9, 10, 11]